/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import com.opencsv.CSVReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;



/**
 *
 * @author marieroca
 */
public class CompetencesFrame extends javax.swing.JFrame {

    /**
     * Creates new form CompetencesFrame
     */
    public CompetencesFrame() {
        initComponents();
        Entreprise ecouteur = new Entreprise(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabNavigation = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pCompetences = new javax.swing.JPanel();
        bParcourirCompetences = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabCompetences = new javax.swing.JTable();
        pPersonnel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabPersonnel = new javax.swing.JTable();
        bParcourirPersonnel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabNavigation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabNavigationMouseClicked(evt);
            }
        });
        tabNavigation.addTab("Missions", jTabbedPane1);

        bParcourirCompetences.setText("Parcourir");
        bParcourirCompetences.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bParcourirCompetencesMouseClicked(evt);
            }
        });

        tabCompetences.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Nom", "Description"
            }
        ));
        jScrollPane2.setViewportView(tabCompetences);

        javax.swing.GroupLayout pCompetencesLayout = new javax.swing.GroupLayout(pCompetences);
        pCompetences.setLayout(pCompetencesLayout);
        pCompetencesLayout.setHorizontalGroup(
            pCompetencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCompetencesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCompetencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCompetencesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bParcourirCompetences))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                .addContainerGap())
        );
        pCompetencesLayout.setVerticalGroup(
            pCompetencesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCompetencesLayout.createSequentialGroup()
                .addComponent(bParcourirCompetences)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
        );

        tabNavigation.addTab("Compétences", pCompetences);

        tabPersonnel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Identifiant", "Prénom", "Nom", "Date d'entrée"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabPersonnel);

        bParcourirPersonnel.setText("Parcourir");
        bParcourirPersonnel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bParcourirPersonnelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pPersonnelLayout = new javax.swing.GroupLayout(pPersonnel);
        pPersonnel.setLayout(pPersonnelLayout);
        pPersonnelLayout.setHorizontalGroup(
            pPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPersonnelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPersonnelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bParcourirPersonnel))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
                .addContainerGap())
        );
        pPersonnelLayout.setVerticalGroup(
            pPersonnelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPersonnelLayout.createSequentialGroup()
                .addComponent(bParcourirPersonnel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
        );

        tabNavigation.addTab("Personnel", pPersonnel);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabNavigation)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabNavigation, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        tabNavigation.getAccessibleContext().setAccessibleName("Missions");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bParcourirCompetencesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bParcourirCompetencesMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            ".csv", "csv");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(pCompetences);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: " +
                chooser.getSelectedFile().getName());
        }
        try {
            CSVReader reader = new CSVReader(new FileReader(chooser.getSelectedFile()));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Competences.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bParcourirCompetencesMouseClicked

    private void bParcourirPersonnelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bParcourirPersonnelMouseClicked
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            ".csv", "csv");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(pCompetences);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: " +
                chooser.getSelectedFile().getName());
        }
    }//GEN-LAST:event_bParcourirPersonnelMouseClicked

    private void tabNavigationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabNavigationMouseClicked

    }//GEN-LAST:event_tabNavigationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompetencesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompetencesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompetencesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompetencesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompetencesFrame().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bParcourirCompetences;
    private javax.swing.JButton bParcourirPersonnel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pCompetences;
    private javax.swing.JPanel pPersonnel;
    private javax.swing.JTable tabCompetences;
    private javax.swing.JTabbedPane tabNavigation;
    private javax.swing.JTable tabPersonnel;
    // End of variables declaration//GEN-END:variables
}
